### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{ 
    "name": "haythytn",
    "company": "fsdfsdf",
    "address": "vfdvfdvfd",
    "phone": "343243243",
    "email": "314@qq.com",
    "password": "123"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "314@qq.com",
    "password": "1234562"
}
### Get User profile
GET  http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMzE0QHFxLmNvbSIsImlhdCI6MTYxNDIwODM1OSwiZXhwIjoxNjE0MjA4Mzc0fQ.WtgenbOXLD4G-n1ZzHzSWL4p_ZnZqBvy-SwFRm5anKs
### Get refresh token
GET  http: //localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMzE0QHFxLmNvbSIsImlhdCI6MTYxNDIwMzUwNSwiZXhwIjoxNjE2Nzk1NTA1fQ.ffToFJTBtiScd9Foc5wJNDtGgoKbDe6pRNjQmbFK4XU

### Request Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "314@qq.com"
}

### Password reset endpoints
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "314@qq.com",
    "pin": "010768",
    "password": "1234562"
    
}
### User logout
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMzE0QHFxLmNvbSIsImlhdCI6MTYxNDQ2ODYzOCwiZXhwIjoxNjE0NDY5NTM4fQ.YbXHbNbMvmENuWoujWuBSysJ7aDBw0FzZIasQwJH6oM